In [1]:
import pandas as pd

supplier_data = [

    # =========================
    # BATTERY SUPPLIERS
    # =========================

    ["S001", "Battery Systems India", "Tamil Nadu",
     "Battery", 15, 85000, 12000, 4.5, 92, "Active"],

    ["S002", "Advanced Energy Systems", "Karnataka",
     "Battery", 18, 88000, 10000, 4.3, 89, "Active"],

    ["S003", "EV Cell Technologies", "Gujarat",
     "Battery", 25, 4200, 500000, 4.2, 87, "Active"],

    ["S004", "PowerCell Manufacturing", "Maharashtra",
     "Battery", 22, 4500, 450000, 4.4, 91, "Active"],


    # =========================
    # POWERTRAIN
    # =========================

    ["S005", "Electric Drive Systems", "Tamil Nadu",
     "Powertrain", 20, 42000, 8000, 4.4, 94, "Active"],

    ["S006", "EV Motor Technologies", "Karnataka",
     "Powertrain", 24, 45000, 7000, 90, 88, "Active"],

    ["S007", "Advanced Drivetrain India", "Maharashtra",
     "Powertrain", 28, 48000, 6000, 4.1, 86, "Active"],


    # =========================
    # POWER ELECTRONICS
    # =========================

    ["S008", "Power Electronics India", "Tamil Nadu",
     "Power Electronics", 18, 28000, 9000, 4.5, 93, "Active"],

    ["S009", "Smart Power Systems", "Karnataka",
     "Power Electronics", 21, 30000, 7500, 4.2, 89, "Active"],

    ["S010", "EV Inverter Technologies", "Gujarat",
     "Power Electronics", 25, 32000, 6000, 4.0, 84, "Active"],


    # =========================
    # CHARGING
    # =========================

    ["S011", "ChargeTech India", "Tamil Nadu",
     "Charging", 12, 18000, 10000, 4.4, 95, "Active"],

    ["S012", "EV Charging Systems", "Maharashtra",
     "Charging", 16, 20000, 8000, 4.1, 88, "Active"],

    ["S013", "Smart Charging Solutions", "Karnataka",
     "Charging", 20, 22000, 6000, 4.0, 85, "Active"],


    # =========================
    # THERMAL MANAGEMENT
    # =========================

    ["S014", "Thermal Systems India", "Tamil Nadu",
     "Thermal", 14, 12000, 9000, 4.3, 92, "Active"],

    ["S015", "EV Cooling Technologies", "Karnataka",
     "Thermal", 18, 13500, 7000, 4.2, 89, "Active"],

    ["S016", "Advanced Thermal Solutions", "Maharashtra",
     "Thermal", 22, 14500, 6000, 4.0, 85, "Active"],


    # =========================
    # ELECTRICAL
    # =========================

    ["S017", "Automotive Wiring India", "Tamil Nadu",
     "Electrical", 10, 7500, 15000, 4.5, 95, "Active"],

    ["S018", "High Voltage Systems India", "Gujarat",
     "Electrical", 17, 9000, 10000, 4.3, 91, "Active"],

    ["S019", "Auto Electrical Technologies", "Maharashtra",
     "Electrical", 15, 8000, 12000, 4.2, 89, "Active"],


    # =========================
    # ELECTRONICS
    # =========================

    ["S020", "Vehicle Electronics India", "Tamil Nadu",
     "Electronics", 20, 16000, 7000, 4.4, 93, "Active"],

    ["S021", "Automotive Control Systems", "Karnataka",
     "Electronics", 24, 18000, 6000, 4.2, 88, "Active"],

    ["S022", "EV Control Technologies", "Maharashtra",
     "Electronics", 27, 19000, 5000, 4.0, 84, "Active"],


    # =========================
    # SAFETY
    # =========================

    ["S023", "Automotive Safety Systems", "Tamil Nadu",
     "Safety", 18, 9500, 8000, 4.4, 92, "Active"],

    ["S024", "EV Safety Technologies", "Karnataka",
     "Safety", 23, 10500, 6000, 4.1, 87, "Active"],


    # =========================
    # MECHANICAL
    # =========================

    ["S025", "Automotive Components India", "Tamil Nadu",
     "Mechanical", 12, 15000, 20000, 4.5, 94, "Active"],

    ["S026", "Vehicle Structure Systems", "Maharashtra",
     "Mechanical", 18, 17000, 15000, 4.3, 90, "Active"],

    ["S027", "Automotive Mechanical Systems", "Karnataka",
     "Mechanical", 20, 18000, 12000, 4.1, 87, "Active"]
]

supplier_master_df = pd.DataFrame(
    supplier_data,
    columns=[
        "supplier_id",
        "supplier_name",
        "location",
        "component_category",
        "lead_time_days",
        "unit_cost",
        "monthly_capacity",
        "quality_rating",
        "reliability_score",
        "status"
    ]
)

print("Shape:", supplier_master_df.shape)

display(supplier_master_df)

Shape: (27, 10)

,supplier_id,supplier_name,location,component_category,lead_time_days,unit_cost,monthly_capacity,quality_rating,reliability_score,status
0,S001,Battery Systems India,Tamil Nadu,Battery,15,85000,12000,4.5,92,Active
1,S002,Advanced Energy Systems,Karnataka,Battery,18,88000,10000,4.3,89,Active
2,S003,EV Cell Technologies,Gujarat,Battery,25,4200,500000,4.2,87,Active
3,S004,PowerCell Manufacturing,Maharashtra,Battery,22,4500,450000,4.4,91,Active
4,S005,Electric Drive Systems,Tamil Nadu,Powertrain,20,42000,8000,4.4,94,Active
5,S006,EV Motor Technologies,Karnataka,Powertrain,24,45000,7000,90.0,88,Active
6,S007,Advanced Drivetrain India,Maharashtra,Powertrain,28,48000,6000,4.1,86,Active
7,S008,Power Electronics India,Tamil Nadu,Power Electronics,18,28000,9000,4.5,93,Active
8,S009,Smart Power Systems,Karnataka,Power Electronics,21,30000,7500,4.2,89,Active
9,S010,EV Inverter Technologies,Gujarat,Power Electronics,25,32000,6000,4.0,84,Active
10,S011,ChargeTech India,Tamil Nadu,Charging,12,18000,10000,4.4,95,Active
11,S012,EV Charging Systems,Maharashtra,Charging,16,20000,8000,4.1,88,Active
12,S013,Smart Charging Solutions,Karnataka,Charging,20,22000,6000,4.0,85,Active
13,S014,Thermal Systems India,Tamil Nadu,Thermal,14,12000,9000,4.3,92,Active
14,S015,EV Cooling Technologies,Karnataka,Thermal,18,13500,7000,4.2,89,Active
15,S016,Advanced Thermal Solutions,Maharashtra,Thermal,22,14500,6000,4.0,85,Active
16,S017,Automotive Wiring India,Tamil Nadu,Electrical,10,7500,15000,4.5,95,Active
17,S018,High Voltage Systems India,Gujarat,Electrical,17,9000,10000,4.3,91,Active
18,S019,Auto Electrical Technologies,Maharashtra,Electrical,15,8000,12000,4.2,89,Active
19,S020,Vehicle Electronics India,Tamil Nadu,Electronics,20,16000,7000,4.4,93,Active
20,S021,Automotive Control Systems,Karnataka,Electronics,24,18000,6000,4.2,88,Active
21,S022,EV Control Technologies,Maharashtra,Electronics,27,19000,5000,4.0,84,Active
22,S023,Automotive Safety Systems,Tamil Nadu,Safety,18,9500,8000,4.4,92,Active
23,S024,EV Safety Technologies,Karnataka,Safety,23,10500,6000,4.1,87,Active
24,S025,Automotive Components India,Tamil Nadu,Mechanical,12,15000,20000,4.5,94,Active
25,S026,Vehicle Structure Systems,Maharashtra,Mechanical,18,17000,15000,4.3,90,Active
26,S027,Automotive Mechanical Systems,Karnataka,Mechanical,20,18000,12000,4.1,87,Active

In [2]:
supplier_component_data = [

    # =========================================================
    # BATTERY
    # =========================================================

    ["S001", "P001", 85000, 15, 100, 12000],
    ["S002", "P001", 88000, 18, 100, 10000],

    ["S003", "P002", 4200, 25, 500, 500000],
    ["S004", "P002", 4500, 22, 500, 450000],

    ["S001", "P003", 3200, 15, 100, 15000],
    ["S002", "P003", 3400, 18, 100, 12000],

    ["S001", "P004", 18000, 17, 100, 10000],
    ["S002", "P004", 19500, 20, 100, 9000],

    ["S001", "P005", 15000, 16, 50, 8000],
    ["S002", "P005", 16500, 19, 50, 7000],

    ["S001", "P006", 8500, 15, 100, 12000],
    ["S002", "P006", 9000, 18, 100, 10000],

    ["S001", "P007", 3200, 15, 100, 12000],
    ["S002", "P007", 3500, 18, 100, 10000],

    ["S001", "P008", 1800, 15, 100, 15000],
    ["S002", "P008", 1950, 19, 100, 12000],

    ["S001", "P009", 6500, 16, 100, 10000],
    ["S002", "P009", 7000, 20, 100, 8000],

    ["S001", "P010", 4200, 15, 100, 10000],
    ["S002", "P010", 4500, 19, 100, 8000],


    # =========================================================
    # POWERTRAIN
    # =========================================================

    ["S005", "P011", 42000, 20, 50, 8000],
    ["S006", "P011", 45000, 24, 50, 7000],
    ["S007", "P011", 48000, 28, 50, 6000],

    ["S005", "P012", 14000, 18, 100, 10000],
    ["S006", "P012", 15000, 22, 100, 8000],

    ["S005", "P013", 28000, 20, 50, 7000],
    ["S007", "P013", 31000, 26, 50, 5000],

    ["S005", "P014", 18000, 20, 50, 7000],
    ["S007", "P014", 20000, 25, 50, 5000],


    # =========================================================
    # POWER ELECTRONICS
    # =========================================================

    ["S008", "P016", 28000, 18, 50, 9000],
    ["S009", "P016", 30000, 21, 50, 7500],
    ["S010", "P016", 32000, 25, 50, 6000],

    ["S008", "P017", 7500, 17, 100, 12000],
    ["S009", "P017", 8200, 21, 100, 9000],

    ["S008", "P018", 16000, 18, 50, 8000],
    ["S009", "P018", 17500, 22, 50, 7000],

    ["S008", "P019", 3200, 17, 200, 15000],
    ["S009", "P019", 3500, 21, 200, 12000],

    ["S008", "P020", 1800, 17, 200, 20000],
    ["S010", "P020", 2100, 24, 200, 15000],


    # =========================================================
    # CHARGING
    # =========================================================

    ["S011", "P021", 18000, 12, 50, 10000],
    ["S012", "P021", 20000, 16, 50, 8000],
    ["S013", "P021", 22000, 20, 50, 6000],

    ["S011", "P022", 4500, 12, 100, 15000],
    ["S012", "P022", 5000, 16, 100, 12000],

    ["S011", "P023", 3500, 12, 100, 15000],
    ["S012", "P023", 3800, 16, 100, 12000],

    ["S011", "P024", 900, 12, 500, 30000],
    ["S013", "P024", 1100, 19, 500, 20000],


    # =========================================================
    # THERMAL
    # =========================================================

    ["S014", "P025", 12000, 14, 50, 9000],
    ["S015", "P025", 13500, 18, 50, 7000],
    ["S016", "P025", 14500, 22, 50, 6000],

    ["S014", "P026", 4500, 14, 100, 12000],
    ["S015", "P026", 5000, 18, 100, 9000],

    ["S014", "P027", 3500, 14, 100, 12000],
    ["S016", "P027", 4000, 21, 100, 8000],

    ["S014", "P028", 7000, 15, 50, 8000],
    ["S016", "P028", 8000, 22, 50, 6000],

    ["S014", "P029", 250, 14, 500, 50000],
    ["S015", "P029", 280, 18, 500, 40000],


    # =========================================================
    # ELECTRICAL
    # =========================================================

    ["S017", "P030", 7500, 10, 500, 15000],
    ["S018", "P030", 9000, 17, 500, 10000],
    ["S019", "P030", 8000, 15, 500, 12000],

    ["S017", "P031", 8500, 10, 100, 15000],
    ["S019", "P031", 9500, 15, 100, 12000],

    ["S017", "P032", 4500, 12, 100, 15000],
    ["S019", "P032", 5000, 16, 100, 12000],


    # =========================================================
    # ELECTRONICS
    # =========================================================

    ["S020", "P034", 16000, 20, 50, 7000],
    ["S021", "P034", 18000, 24, 50, 6000],

    ["S020", "P035", 8500, 20, 100, 8000],
    ["S021", "P035", 9500, 24, 100, 6000],

    ["S020", "P036", 6000, 20, 100, 8000],
    ["S021", "P036", 7000, 24, 100, 6000],

    ["S020", "P037", 12000, 20, 50, 7000],
    ["S022", "P037", 13500, 27, 50, 5000],


    # =========================================================
    # SAFETY
    # =========================================================

    ["S023", "P038", 9500, 18, 100, 8000],
    ["S024", "P038", 10500, 23, 100, 6000],

    ["S023", "P039", 1800, 18, 200, 15000],
    ["S024", "P039", 2100, 23, 200, 10000],

    ["S023", "P040", 3500, 18, 100, 8000],
    ["S024", "P040", 4000, 23, 100, 6000],


    # =========================================================
    # MECHANICAL
    # =========================================================

    ["S025", "P041", 55000, 12, 20, 5000],
    ["S026", "P041", 58000, 18, 20, 4000],

    ["S025", "P042", 12000, 12, 50, 10000],
    ["S026", "P042", 13500, 18, 50, 8000],

    ["S025", "P043", 8500, 12, 50, 12000],
    ["S026", "P043", 9500, 18, 50, 9000],

    ["S025", "P044", 14000, 13, 50, 8000],
    ["S026", "P044", 15500, 19, 50, 6000],

    ["S025", "P045", 10000, 12, 100, 15000],
    ["S026", "P045", 11500, 18, 100, 12000]
]

In [3]:
supplier_component_df = pd.DataFrame(
    supplier_component_data,
    columns=[
        "supplier_id",
        "part_id",
        "unit_cost",
        "lead_time_days",
        "minimum_order_quantity",
        "monthly_capacity"
    ]
)

print("Shape:", supplier_component_df.shape)

display(supplier_component_df.head(20))

Shape: (91, 6)

,supplier_id,part_id,unit_cost,lead_time_days,minimum_order_quantity,monthly_capacity
0,S001,P001,85000,15,100,12000
1,S002,P001,88000,18,100,10000
2,S003,P002,4200,25,500,500000
3,S004,P002,4500,22,500,450000
4,S001,P003,3200,15,100,15000
5,S002,P003,3400,18,100,12000
6,S001,P004,18000,17,100,10000
7,S002,P004,19500,20,100,9000
8,S001,P005,15000,16,50,8000
9,S002,P005,16500,19,50,7000
10,S001,P006,8500,15,100,12000
11,S002,P006,9000,18,100,10000
12,S001,P007,3200,15,100,12000
13,S002,P007,3500,18,100,10000
14,S001,P008,1800,15,100,15000
15,S002,P008,1950,19,100,12000
16,S001,P009,6500,16,100,10000
17,S002,P009,7000,20,100,8000
18,S001,P010,4200,15,100,10000
19,S002,P010,4500,19,100,8000

In [5]:
supplier_network_df = supplier_component_df.merge(
    supplier_master_df,
    on="supplier_id",
    how="left",
    suffixes=("_component", "_supplier")
)

display(supplier_network_df.head())

,supplier_id,part_id,unit_cost_component,lead_time_days_component,minimum_order_quantity,monthly_capacity_component,supplier_name,location,component_category,lead_time_days_supplier,unit_cost_supplier,monthly_capacity_supplier,quality_rating,reliability_score,status
0,S001,P001,85000,15,100,12000,Battery Systems India,Tamil Nadu,Battery,15,85000,12000,4.5,92,Active
1,S002,P001,88000,18,100,10000,Advanced Energy Systems,Karnataka,Battery,18,88000,10000,4.3,89,Active
2,S003,P002,4200,25,500,500000,EV Cell Technologies,Gujarat,Battery,25,4200,500000,4.2,87,Active
3,S004,P002,4500,22,500,450000,PowerCell Manufacturing,Maharashtra,Battery,22,4500,450000,4.4,91,Active
4,S001,P003,3200,15,100,15000,Battery Systems India,Tamil Nadu,Battery,15,85000,12000,4.5,92,Active

In [7]:
import pandas as pd
import numpy as np

np.random.seed(42)

# Number of purchase orders
N = 2000

# Available suppliers/components
supplier_ids = supplier_component_df["supplier_id"].unique()
part_ids = supplier_component_df["part_id"].unique()

warehouses = [
    "Chennai",
    "Hosur",
    "Coimbatore",
    "Chengalpattu"
]

po_data = []

for i in range(N):

    # Select supplier-component relationship
    relationship = supplier_component_df.sample(1).iloc[0]

    supplier_id = relationship["supplier_id"]
    part_id = relationship["part_id"]

    # Supplier-specific information
    lead_time = int(relationship["lead_time_days"])
    unit_cost = float(relationship["unit_cost"])

    # PO date
    po_date = pd.Timestamp(
        np.random.choice(
            pd.date_range(
                "2025-01-01",
                "2026-08-31"
            )
        )
    )

    # Ordered quantity
    quantity_ordered = int(
        np.random.randint(
            100,
            2000
        )
    )

    # Random delivery behavior
    delivery_behavior = np.random.choice(
        ["On Time", "Late", "Partial", "Late + Partial"],
        p=[0.60, 0.20, 0.12, 0.08]
    )

    # Expected delivery
    expected_date = (
        po_date +
        pd.Timedelta(days=lead_time)
    )

    # Actual delivery
    if delivery_behavior == "On Time":

        delay = np.random.randint(-2, 3)

        actual_date = (
            expected_date +
            pd.Timedelta(days=delay)
        )

        quantity_received = quantity_ordered

        status = "Delivered"

    elif delivery_behavior == "Late":

        delay = np.random.randint(3, 15)

        actual_date = (
            expected_date +
            pd.Timedelta(days=delay)
        )

        quantity_received = quantity_ordered

        status = "Late"

    elif delivery_behavior == "Partial":

        delay = np.random.randint(-1, 4)

        actual_date = (
            expected_date +
            pd.Timedelta(days=delay)
        )

        quantity_received = int(
            quantity_ordered *
            np.random.uniform(0.60, 0.95)
        )

        status = "Partial"

    else:

        delay = np.random.randint(3, 15)

        actual_date = (
            expected_date +
            pd.Timedelta(days=delay)
        )

        quantity_received = int(
            quantity_ordered *
            np.random.uniform(0.50, 0.90)
        )

        status = "Late + Partial"

    warehouse = np.random.choice(warehouses)

    po_data.append([
        f"PO{i+1:05d}",
        po_date,
        supplier_id,
        part_id,
        warehouse,
        quantity_ordered,
        quantity_received,
        unit_cost,
        expected_date,
        actual_date,
        status
    ])

In [8]:
purchase_order_df = pd.DataFrame(
    po_data,
    columns=[
        "po_id",
        "po_date",
        "supplier_id",
        "part_id",
        "warehouse",
        "quantity_ordered",
        "quantity_received",
        "unit_cost",
        "expected_delivery_date",
        "actual_delivery_date",
        "order_status"
    ]
)

print("Shape:", purchase_order_df.shape)

display(
    purchase_order_df.head(20)
)

Shape: (2000, 11)

,po_id,po_date,supplier_id,part_id,warehouse,quantity_ordered,quantity_received,unit_cost,expected_delivery_date,actual_delivery_date,order_status
0,PO00001,2025-12-10,S011,P021,Coimbatore,1252,1252,18000.0,2025-12-22,2025-12-22,Delivered
1,PO00002,2026-05-12,S011,P023,Chennai,541,378,3500.0,2026-05-24,2026-06-02,Late + Partial
2,PO00003,2025-06-10,S002,P005,Chengalpattu,1703,1703,16500.0,2025-06-29,2025-07-01,Delivered
3,PO00004,2025-04-02,S015,P029,Chennai,1477,1477,280.0,2025-04-20,2025-04-20,Delivered
4,PO00005,2025-11-21,S005,P012,Hosur,615,615,14000.0,2025-12-09,2025-12-18,Late
5,PO00006,2026-07-19,S009,P016,Chennai,1274,1274,30000.0,2026-08-09,2026-08-18,Late
6,PO00007,2026-02-19,S020,P036,Coimbatore,1636,1636,6000.0,2026-03-11,2026-03-19,Late
7,PO00008,2025-04-28,S025,P041,Chennai,870,870,55000.0,2025-05-10,2025-05-11,Delivered
8,PO00009,2025-01-26,S014,P027,Chengalpattu,903,730,3500.0,2025-02-09,2025-02-08,Partial
9,PO00010,2025-11-22,S017,P032,Chengalpattu,1533,1533,4500.0,2025-12-04,2025-12-04,Delivered
10,PO00011,2026-01-26,S008,P020,Coimbatore,1302,1302,1800.0,2026-02-12,2026-02-13,Delivered
11,PO00012,2025-05-17,S017,P030,Coimbatore,301,244,7500.0,2025-05-27,2025-05-30,Partial
12,PO00013,2026-04-14,S024,P038,Coimbatore,1009,1009,10500.0,2026-05-07,2026-05-06,Delivered
13,PO00014,2025-10-19,S003,P002,Coimbatore,1494,1494,4200.0,2025-11-13,2025-11-15,Delivered
14,PO00015,2025-09-30,S020,P035,Chengalpattu,1649,1649,8500.0,2025-10-20,2025-10-20,Delivered
15,PO00016,2025-02-23,S016,P028,Coimbatore,1170,1170,8000.0,2025-03-17,2025-03-15,Delivered
16,PO00017,2026-06-08,S002,P006,Hosur,394,394,9000.0,2026-06-26,2026-06-28,Delivered
17,PO00018,2025-03-01,S002,P004,Chennai,529,529,19500.0,2025-03-21,2025-03-23,Delivered
18,PO00019,2025-01-09,S013,P021,Hosur,873,873,22000.0,2025-01-29,2025-02-09,Late
19,PO00020,2026-06-04,S021,P036,Hosur,199,135,7000.0,2026-06-28,2026-06-28,Partial

In [9]:
purchase_order_df["quantity_shortage"] = (
    purchase_order_df["quantity_ordered"]
    -
    purchase_order_df["quantity_received"]
)

In [10]:
purchase_order_df["delivery_delay_days"] = (
    purchase_order_df["actual_delivery_date"]
    -
    purchase_order_df["expected_delivery_date"]
).dt.days

In [11]:
purchase_order_df["order_value"] = (
    purchase_order_df["quantity_ordered"]
    *
    purchase_order_df["unit_cost"]
)

In [12]:
display(
    purchase_order_df.head()
)

,po_id,po_date,supplier_id,part_id,warehouse,quantity_ordered,quantity_received,unit_cost,expected_delivery_date,actual_delivery_date,order_status,quantity_shortage,delivery_delay_days,order_value
0,PO00001,2025-12-10,S011,P021,Coimbatore,1252,1252,18000.0,2025-12-22,2025-12-22,Delivered,0,0,22536000.0
1,PO00002,2026-05-12,S011,P023,Chennai,541,378,3500.0,2026-05-24,2026-06-02,Late + Partial,163,9,1893500.0
2,PO00003,2025-06-10,S002,P005,Chengalpattu,1703,1703,16500.0,2025-06-29,2025-07-01,Delivered,0,2,28099500.0
3,PO00004,2025-04-02,S015,P029,Chennai,1477,1477,280.0,2025-04-20,2025-04-20,Delivered,0,0,413560.0
4,PO00005,2025-11-21,S005,P012,Hosur,615,615,14000.0,2025-12-09,2025-12-18,Late,0,9,8610000.0

In [13]:
supplier_performance = (
    purchase_order_df
    .groupby("supplier_id")
    .agg(
        total_orders=("po_id", "count"),
        total_ordered=("quantity_ordered", "sum"),
        total_received=("quantity_received", "sum"),
        average_delay_days=("delivery_delay_days", "mean"),
        total_shortage=("quantity_shortage", "sum")
    )
    .reset_index()
)

display(
    supplier_performance.sort_values(
        "average_delay_days",
        ascending=False
    )
)

,supplier_id,total_orders,total_ordered,total_received,average_delay_days,total_shortage
17,S018,21,18884,17669,3.571429,1215
16,S017,62,58927,55938,3.274194,2989
8,S009,94,105432,99804,2.914894,5628
15,S016,56,58195,55333,2.857143,2862
14,S015,58,62299,59922,2.758621,2377
24,S025,104,103855,98710,2.750000,5145
19,S020,80,89503,86736,2.700000,2767
11,S012,62,66857,63092,2.693548,3765
5,S006,44,50322,47359,2.590909,2963
9,S010,37,38620,36055,2.351351,2565
0,S001,178,175358,168934,2.325843,6424
13,S014,108,106804,98898,2.287037,7906
7,S008,109,110626,105983,2.275229,4643
23,S024,80,84212,81943,2.262500,2269
10,S011,105,110869,103300,2.238095,7569
20,S021,65,77516,74578,2.215385,2938
18,S019,65,66569,61130,2.200000,5439
25,S026,114,133032,127633,2.175439,5399
1,S002,207,213374,206978,2.091787,6396
6,S007,69,78880,75713,2.072464,3167
12,S013,59,62053,59707,2.016949,2346
22,S023,71,69804,66160,2.014085,3644
4,S005,88,82112,78798,1.931818,3314
2,S003,19,27043,26134,1.894737,909
21,S022,25,25583,25120,1.440000,463
3,S004,20,19616,19150,1.200000,466

In [14]:
supplier_performance["fulfillment_rate"] = (
    supplier_performance["total_received"]
    /
    supplier_performance["total_ordered"]
) * 100

In [15]:
display(
    supplier_performance.sort_values(
        "fulfillment_rate"
    )
)

,supplier_id,total_orders,total_ordered,total_received,average_delay_days,total_shortage,fulfillment_rate
18,S019,65,66569,61130,2.200000,5439,91.829530
13,S014,108,106804,98898,2.287037,7906,92.597656
10,S011,105,110869,103300,2.238095,7569,93.173024
9,S010,37,38620,36055,2.351351,2565,93.358364
17,S018,21,18884,17669,3.571429,1215,93.565982
5,S006,44,50322,47359,2.590909,2963,94.111919
11,S012,62,66857,63092,2.693548,3765,94.368578
8,S009,94,105432,99804,2.914894,5628,94.661962
22,S023,71,69804,66160,2.014085,3644,94.779669
16,S017,62,58927,55938,3.274194,2989,94.927622
24,S025,104,103855,98710,2.750000,5145,95.045978
15,S016,56,58195,55333,2.857143,2862,95.082052
7,S008,109,110626,105983,2.275229,4643,95.802976
25,S026,114,133032,127633,2.175439,5399,95.941578
4,S005,88,82112,78798,1.931818,3314,95.964049
6,S007,69,78880,75713,2.072464,3167,95.985041
14,S015,58,62299,59922,2.758621,2377,96.184529
20,S021,65,77516,74578,2.215385,2938,96.209815
12,S013,59,62053,59707,2.016949,2346,96.219361
0,S001,178,175358,168934,2.325843,6424,96.336637
2,S003,19,27043,26134,1.894737,909,96.638687
19,S020,80,89503,86736,2.700000,2767,96.908484
1,S002,207,213374,206978,2.091787,6396,97.002446
23,S024,80,84212,81943,2.262500,2269,97.305610
3,S004,20,19616,19150,1.200000,466,97.624388
21,S022,25,25583,25120,1.440000,463,98.190204