In [2]:
import pandas as pd

vehicle_data = [
    ["EV001", "Electric 2W", "Two Wheeler", "Personal Mobility"],
    ["EV002", "Electric 3W Passenger", "Three Wheeler", "Passenger Transport"],
    ["EV003", "Electric 3W Goods", "Three Wheeler", "Goods Transport"],
    ["EV004", "Electric Car", "Passenger Vehicle", "Passenger Transport"],
    ["EV005", "Electric LGV", "Commercial Vehicle", "Goods Transport"],
    ["EV006", "Electric Bus", "Commercial Vehicle", "Public Transport"],
    ["EV007", "Electric HGV/Truck", "Commercial Vehicle", "Heavy Goods Transport"]
]

vehicle_master_df = pd.DataFrame(
    vehicle_data,
    columns=[
        "vehicle_id",
        "vehicle_type",
        "vehicle_category",
        "use_case"
    ]
)

print("Shape:", vehicle_master_df.shape)

display(vehicle_master_df)

Shape: (7, 4)

  vehicle_id           vehicle_type    vehicle_category               use_case
0      EV001            Electric 2W         Two Wheeler      Personal Mobility
1      EV002  Electric 3W Passenger       Three Wheeler    Passenger Transport
2      EV003      Electric 3W Goods       Three Wheeler        Goods Transport
3      EV004           Electric Car   Passenger Vehicle    Passenger Transport
4      EV005           Electric LGV  Commercial Vehicle        Goods Transport
5      EV006           Electric Bus  Commercial Vehicle       Public Transport
6      EV007     Electric HGV/Truck  Commercial Vehicle  Heavy Goods Transport

In [3]:
import pandas as pd

component_data = [

    # =========================
    # BATTERY SYSTEM
    # =========================
    ["P001", "Battery Pack", "Battery", "Energy Storage", "Unit", "Critical"],
    ["P002", "Battery Cells", "Battery", "Energy Storage", "Unit", "Critical"],
    ["P003", "Battery Management System", "Battery", "Battery Control", "Unit", "Critical"],
    ["P004", "Battery Module", "Battery", "Energy Storage", "Unit", "Critical"],
    ["P005", "Battery Enclosure", "Battery", "Mechanical", "Unit", "High"],
    ["P006", "Busbar", "Battery", "Electrical Connection", "Unit", "High"],
    ["P007", "Cell Connector", "Battery", "Electrical Connection", "Unit", "High"],
    ["P008", "Battery Sensor", "Battery", "Monitoring", "Unit", "High"],
    ["P009", "Battery Cooling Plate", "Battery", "Thermal", "Unit", "High"],
    ["P010", "Battery Safety Disconnect", "Battery", "Safety", "Unit", "Critical"],

    # =========================
    # ELECTRIC POWERTRAIN
    # =========================
    ["P011", "Electric Motor", "Powertrain", "Traction Motor", "Unit", "Critical"],
    ["P012", "Motor Controller", "Powertrain", "Motor Control", "Unit", "Critical"],
    ["P013", "Reduction Gearbox", "Powertrain", "Transmission", "Unit", "High"],
    ["P014", "Differential", "Powertrain", "Transmission", "Unit", "High"],
    ["P015", "Drive Shaft", "Powertrain", "Transmission", "Unit", "Medium"],

    # =========================
    # POWER ELECTRONICS
    # =========================
    ["P016", "Inverter", "Power Electronics", "Power Conversion", "Unit", "Critical"],
    ["P017", "DC-DC Converter", "Power Electronics", "Power Conversion", "Unit", "High"],
    ["P018", "Power Distribution Unit", "Power Electronics", "Power Distribution", "Unit", "High"],
    ["P019", "High Voltage Contactor", "Power Electronics", "Switching", "Unit", "Critical"],
    ["P020", "High Voltage Fuse", "Power Electronics", "Protection", "Unit", "High"],

    # =========================
    # CHARGING SYSTEM
    # =========================
    ["P021", "On-board Charger", "Charging", "Charging System", "Unit", "High"],
    ["P022", "Charging Port", "Charging", "Charging Interface", "Unit", "Medium"],
    ["P023", "Charging Cable", "Charging", "Charging Interface", "Unit", "Medium"],
    ["P024", "High Voltage Connector", "Charging", "Electrical Connection", "Unit", "High"],

    # =========================
    # THERMAL MANAGEMENT
    # =========================
    ["P025", "Thermal Management System", "Thermal", "Thermal Control", "Unit", "High"],
    ["P026", "Cooling Pump", "Thermal", "Cooling", "Unit", "Medium"],
    ["P027", "Cooling Fan", "Thermal", "Cooling", "Unit", "Medium"],
    ["P028", "Radiator", "Thermal", "Cooling", "Unit", "Medium"],
    ["P029", "Coolant", "Thermal", "Fluid", "Liter", "Medium"],

    # =========================
    # ELECTRICAL SYSTEM
    # =========================
    ["P030", "High Voltage Cable", "Electrical", "High Voltage", "Meter", "High"],
    ["P031", "Wiring Harness", "Electrical", "Wiring", "Unit", "High"],
    ["P032", "12V Auxiliary Battery", "Electrical", "Auxiliary Power", "Unit", "Medium"],
    ["P033", "Low Voltage Connector", "Electrical", "Connection", "Unit", "Medium"],

    # =========================
    # CONTROL & ELECTRONICS
    # =========================
    ["P034", "Vehicle Control Unit", "Electronics", "Vehicle Control", "Unit", "Critical"],
    ["P035", "Electronic Control Module", "Electronics", "Control", "Unit", "High"],
    ["P036", "CAN Communication Module", "Electronics", "Communication", "Unit", "High"],
    ["P037", "Vehicle Display Unit", "Electronics", "HMI", "Unit", "Medium"],

    # =========================
    # SAFETY
    # =========================
    ["P038", "Insulation Monitoring Device", "Safety", "Electrical Safety", "Unit", "Critical"],
    ["P039", "Crash Sensor", "Safety", "Vehicle Safety", "Unit", "High"],
    ["P040", "Emergency Disconnect", "Safety", "Battery Safety", "Unit", "Critical"],

    # =========================
    # MECHANICAL
    # =========================
    ["P041", "Vehicle Chassis", "Mechanical", "Structure", "Unit", "High"],
    ["P042", "Suspension Assembly", "Mechanical", "Suspension", "Unit", "Medium"],
    ["P043", "Brake Assembly", "Mechanical", "Braking", "Unit", "High"],
    ["P044", "Steering Assembly", "Mechanical", "Steering", "Unit", "High"],
    ["P045", "Wheel Assembly", "Mechanical", "Wheel", "Unit", "Medium"]
]

component_master_df = pd.DataFrame(
    component_data,
    columns=[
        "part_id",
        "part_name",
        "category",
        "sub_category",
        "unit",
        "criticality"
    ]
)

print("Shape:", component_master_df.shape)

display(component_master_df)

Shape: (45, 6)

,part_id,part_name,category,sub_category,unit,criticality
0,P001,Battery Pack,Battery,Energy Storage,Unit,Critical
1,P002,Battery Cells,Battery,Energy Storage,Unit,Critical
2,P003,Battery Management System,Battery,Battery Control,Unit,Critical
3,P004,Battery Module,Battery,Energy Storage,Unit,Critical
4,P005,Battery Enclosure,Battery,Mechanical,Unit,High
5,P006,Busbar,Battery,Electrical Connection,Unit,High
6,P007,Cell Connector,Battery,Electrical Connection,Unit,High
7,P008,Battery Sensor,Battery,Monitoring,Unit,High
8,P009,Battery Cooling Plate,Battery,Thermal,Unit,High
9,P010,Battery Safety Disconnect,Battery,Safety,Unit,Critical
10,P011,Electric Motor,Powertrain,Traction Motor,Unit,Critical
11,P012,Motor Controller,Powertrain,Motor Control,Unit,Critical
12,P013,Reduction Gearbox,Powertrain,Transmission,Unit,High
13,P014,Differential,Powertrain,Transmission,Unit,High
14,P015,Drive Shaft,Powertrain,Transmission,Unit,Medium
15,P016,Inverter,Power Electronics,Power Conversion,Unit,Critical
16,P017,DC-DC Converter,Power Electronics,Power Conversion,Unit,High
17,P018,Power Distribution Unit,Power Electronics,Power Distribution,Unit,High
18,P019,High Voltage Contactor,Power Electronics,Switching,Unit,Critical
19,P020,High Voltage Fuse,Power Electronics,Protection,Unit,High
20,P021,On-board Charger,Charging,Charging System,Unit,High
21,P022,Charging Port,Charging,Charging Interface,Unit,Medium
22,P023,Charging Cable,Charging,Charging Interface,Unit,Medium
23,P024,High Voltage Connector,Charging,Electrical Connection,Unit,High
24,P025,Thermal Management System,Thermal,Thermal Control,Unit,High
25,P026,Cooling Pump,Thermal,Cooling,Unit,Medium
26,P027,Cooling Fan,Thermal,Cooling,Unit,Medium
27,P028,Radiator,Thermal,Cooling,Unit,Medium
28,P029,Coolant,Thermal,Fluid,Liter,Medium
29,P030,High Voltage Cable,Electrical,High Voltage,Meter,High
30,P031,Wiring Harness,Electrical,Wiring,Unit,High
31,P032,12V Auxiliary Battery,Electrical,Auxiliary Power,Unit,Medium
32,P033,Low Voltage Connector,Electrical,Connection,Unit,Medium
33,P034,Vehicle Control Unit,Electronics,Vehicle Control,Unit,Critical
34,P035,Electronic Control Module,Electronics,Control,Unit,High
35,P036,CAN Communication Module,Electronics,Communication,Unit,High
36,P037,Vehicle Display Unit,Electronics,HMI,Unit,Medium
37,P038,Insulation Monitoring Device,Safety,Electrical Safety,Unit,Critical
38,P039,Crash Sensor,Safety,Vehicle Safety,Unit,High
39,P040,Emergency Disconnect,Safety,Battery Safety,Unit,Critical
40,P041,Vehicle Chassis,Mechanical,Structure,Unit,High
41,P042,Suspension Assembly,Mechanical,Suspension,Unit,Medium
42,P043,Brake Assembly,Mechanical,Braking,Unit,High
43,P044,Steering Assembly,Mechanical,Steering,Unit,High
44,P045,Wheel Assembly,Mechanical,Wheel,Unit,Medium

In [4]:
bom_data = [

    # ==========================================================
    # ELECTRIC 2W
    # ==========================================================

    ["EV001", "Electric 2W", "P001", "Battery Pack", 1, "Unit"],
    ["EV001", "Electric 2W", "P002", "Battery Cells", 1, "Set"],
    ["EV001", "Electric 2W", "P003", "Battery Management System", 1, "Unit"],
    ["EV001", "Electric 2W", "P011", "Electric Motor", 1, "Unit"],
    ["EV001", "Electric 2W", "P012", "Motor Controller", 1, "Unit"],
    ["EV001", "Electric 2W", "P017", "DC-DC Converter", 1, "Unit"],
    ["EV001", "Electric 2W", "P022", "Charging Port", 1, "Unit"],
    ["EV001", "Electric 2W", "P023", "Charging Cable", 1, "Unit"],
    ["EV001", "Electric 2W", "P030", "High Voltage Cable", 1, "Meter"],
    ["EV001", "Electric 2W", "P031", "Wiring Harness", 1, "Unit"],
    ["EV001", "Electric 2W", "P032", "12V Auxiliary Battery", 1, "Unit"],


    # ==========================================================
    # ELECTRIC 3W PASSENGER
    # ==========================================================

    ["EV002", "Electric 3W Passenger", "P001", "Battery Pack", 1, "Unit"],
    ["EV002", "Electric 3W Passenger", "P002", "Battery Cells", 1, "Set"],
    ["EV002", "Electric 3W Passenger", "P003", "Battery Management System", 1, "Unit"],
    ["EV002", "Electric 3W Passenger", "P011", "Electric Motor", 1, "Unit"],
    ["EV002", "Electric 3W Passenger", "P012", "Motor Controller", 1, "Unit"],
    ["EV002", "Electric 3W Passenger", "P016", "Inverter", 1, "Unit"],
    ["EV002", "Electric 3W Passenger", "P017", "DC-DC Converter", 1, "Unit"],
    ["EV002", "Electric 3W Passenger", "P022", "Charging Port", 1, "Unit"],
    ["EV002", "Electric 3W Passenger", "P023", "Charging Cable", 1, "Unit"],
    ["EV002", "Electric 3W Passenger", "P030", "High Voltage Cable", 2, "Meter"],
    ["EV002", "Electric 3W Passenger", "P031", "Wiring Harness", 1, "Unit"],
    ["EV002", "Electric 3W Passenger", "P032", "12V Auxiliary Battery", 1, "Unit"],


    # ==========================================================
    # ELECTRIC 3W GOODS
    # ==========================================================

    ["EV003", "Electric 3W Goods", "P001", "Battery Pack", 1, "Unit"],
    ["EV003", "Electric 3W Goods", "P002", "Battery Cells", 1, "Set"],
    ["EV003", "Electric 3W Goods", "P003", "Battery Management System", 1, "Unit"],
    ["EV003", "Electric 3W Goods", "P011", "Electric Motor", 1, "Unit"],
    ["EV003", "Electric 3W Goods", "P012", "Motor Controller", 1, "Unit"],
    ["EV003", "Electric 3W Goods", "P016", "Inverter", 1, "Unit"],
    ["EV003", "Electric 3W Goods", "P017", "DC-DC Converter", 1, "Unit"],
    ["EV003", "Electric 3W Goods", "P022", "Charging Port", 1, "Unit"],
    ["EV003", "Electric 3W Goods", "P023", "Charging Cable", 1, "Unit"],
    ["EV003", "Electric 3W Goods", "P030", "High Voltage Cable", 2, "Meter"],
    ["EV003", "Electric 3W Goods", "P031", "Wiring Harness", 1, "Unit"],
    ["EV003", "Electric 3W Goods", "P032", "12V Auxiliary Battery", 1, "Unit"],


    # ==========================================================
    # ELECTRIC CAR
    # ==========================================================

    ["EV004", "Electric Car", "P001", "Battery Pack", 1, "Unit"],
    ["EV004", "Electric Car", "P002", "Battery Cells", 1, "Set"],
    ["EV004", "Electric Car", "P003", "Battery Management System", 1, "Unit"],
    ["EV004", "Electric Car", "P004", "Battery Module", 1, "Unit"],
    ["EV004", "Electric Car", "P005", "Battery Enclosure", 1, "Unit"],
    ["EV004", "Electric Car", "P006", "Busbar", 1, "Set"],
    ["EV004", "Electric Car", "P007", "Cell Connector", 1, "Set"],
    ["EV004", "Electric Car", "P008", "Battery Sensor", 4, "Unit"],
    ["EV004", "Electric Car", "P009", "Battery Cooling Plate", 1, "Unit"],
    ["EV004", "Electric Car", "P010", "Battery Safety Disconnect", 1, "Unit"],

    ["EV004", "Electric Car", "P011", "Electric Motor", 1, "Unit"],
    ["EV004", "Electric Car", "P012", "Motor Controller", 1, "Unit"],
    ["EV004", "Electric Car", "P013", "Reduction Gearbox", 1, "Unit"],
    ["EV004", "Electric Car", "P014", "Differential", 1, "Unit"],

    ["EV004", "Electric Car", "P016", "Inverter", 1, "Unit"],
    ["EV004", "Electric Car", "P017", "DC-DC Converter", 1, "Unit"],
    ["EV004", "Electric Car", "P018", "Power Distribution Unit", 1, "Unit"],
    ["EV004", "Electric Car", "P019", "High Voltage Contactor", 4, "Unit"],
    ["EV004", "Electric Car", "P020", "High Voltage Fuse", 2, "Unit"],

    ["EV004", "Electric Car", "P021", "On-board Charger", 1, "Unit"],
    ["EV004", "Electric Car", "P022", "Charging Port", 1, "Unit"],
    ["EV004", "Electric Car", "P023", "Charging Cable", 1, "Unit"],
    ["EV004", "Electric Car", "P024", "High Voltage Connector", 6, "Unit"],

    ["EV004", "Electric Car", "P025", "Thermal Management System", 1, "Unit"],
    ["EV004", "Electric Car", "P026", "Cooling Pump", 2, "Unit"],
    ["EV004", "Electric Car", "P027", "Cooling Fan", 2, "Unit"],
    ["EV004", "Electric Car", "P028", "Radiator", 1, "Unit"],
    ["EV004", "Electric Car", "P029", "Coolant", 8, "Liter"],

    ["EV004", "Electric Car", "P030", "High Voltage Cable", 8, "Meter"],
    ["EV004", "Electric Car", "P031", "Wiring Harness", 1, "Unit"],
    ["EV004", "Electric Car", "P032", "12V Auxiliary Battery", 1, "Unit"],
    ["EV004", "Electric Car", "P034", "Vehicle Control Unit", 1, "Unit"],
    ["EV004", "Electric Car", "P035", "Electronic Control Module", 3, "Unit"],
    ["EV004", "Electric Car", "P036", "CAN Communication Module", 1, "Unit"],
    ["EV004", "Electric Car", "P037", "Vehicle Display Unit", 1, "Unit"],

    ["EV004", "Electric Car", "P038", "Insulation Monitoring Device", 1, "Unit"],
    ["EV004", "Electric Car", "P039", "Crash Sensor", 4, "Unit"],
    ["EV004", "Electric Car", "P040", "Emergency Disconnect", 1, "Unit"],

    ["EV004", "Electric Car", "P041", "Vehicle Chassis", 1, "Unit"],
    ["EV004", "Electric Car", "P042", "Suspension Assembly", 4, "Unit"],
    ["EV004", "Electric Car", "P043", "Brake Assembly", 4, "Unit"],
    ["EV004", "Electric Car", "P044", "Steering Assembly", 1, "Unit"],
    ["EV004", "Electric Car", "P045", "Wheel Assembly", 4, "Unit"],


    # ==========================================================
    # ELECTRIC LGV
    # ==========================================================

    ["EV005", "Electric LGV", "P001", "Battery Pack", 1, "Unit"],
    ["EV005", "Electric LGV", "P003", "Battery Management System", 1, "Unit"],
    ["EV005", "Electric LGV", "P004", "Battery Module", 2, "Unit"],
    ["EV005", "Electric LGV", "P011", "Electric Motor", 1, "Unit"],
    ["EV005", "Electric LGV", "P012", "Motor Controller", 1, "Unit"],
    ["EV005", "Electric LGV", "P013", "Reduction Gearbox", 1, "Unit"],
    ["EV005", "Electric LGV", "P016", "Inverter", 1, "Unit"],
    ["EV005", "Electric LGV", "P017", "DC-DC Converter", 1, "Unit"],
    ["EV005", "Electric LGV", "P018", "Power Distribution Unit", 1, "Unit"],
    ["EV005", "Electric LGV", "P021", "On-board Charger", 1, "Unit"],
    ["EV005", "Electric LGV", "P022", "Charging Port", 1, "Unit"],
    ["EV005", "Electric LGV", "P024", "High Voltage Connector", 6, "Unit"],
    ["EV005", "Electric LGV", "P025", "Thermal Management System", 1, "Unit"],
    ["EV005", "Electric LGV", "P026", "Cooling Pump", 2, "Unit"],
    ["EV005", "Electric LGV", "P030", "High Voltage Cable", 10, "Meter"],
    ["EV005", "Electric LGV", "P031", "Wiring Harness", 1, "Unit"],
    ["EV005", "Electric LGV", "P032", "12V Auxiliary Battery", 1, "Unit"],
    ["EV005", "Electric LGV", "P034", "Vehicle Control Unit", 1, "Unit"],
    ["EV005", "Electric LGV", "P038", "Insulation Monitoring Device", 1, "Unit"],


    # ==========================================================
    # ELECTRIC BUS
    # ==========================================================

    ["EV006", "Electric Bus", "P001", "Battery Pack", 1, "Unit"],
    ["EV006", "Electric Bus", "P002", "Battery Cells", 1, "Set"],
    ["EV006", "Electric Bus", "P003", "Battery Management System", 1, "Unit"],
    ["EV006", "Electric Bus", "P004", "Battery Module", 8, "Unit"],
    ["EV006", "Electric Bus", "P005", "Battery Enclosure", 2, "Unit"],
    ["EV006", "Electric Bus", "P009", "Battery Cooling Plate", 8, "Unit"],
    ["EV006", "Electric Bus", "P010", "Battery Safety Disconnect", 2, "Unit"],

    ["EV006", "Electric Bus", "P011", "Electric Motor", 2, "Unit"],
    ["EV006", "Electric Bus", "P012", "Motor Controller", 2, "Unit"],
    ["EV006", "Electric Bus", "P013", "Reduction Gearbox", 2, "Unit"],
    ["EV006", "Electric Bus", "P014", "Differential", 2, "Unit"],

    ["EV006", "Electric Bus", "P016", "Inverter", 2, "Unit"],
    ["EV006", "Electric Bus", "P017", "DC-DC Converter", 2, "Unit"],
    ["EV006", "Electric Bus", "P018", "Power Distribution Unit", 2, "Unit"],
    ["EV006", "Electric Bus", "P019", "High Voltage Contactor", 8, "Unit"],
    ["EV006", "Electric Bus", "P020", "High Voltage Fuse", 4, "Unit"],

    ["EV006", "Electric Bus", "P021", "On-board Charger", 2, "Unit"],
    ["EV006", "Electric Bus", "P022", "Charging Port", 2, "Unit"],
    ["EV006", "Electric Bus", "P024", "High Voltage Connector", 12, "Unit"],

    ["EV006", "Electric Bus", "P025", "Thermal Management System", 2, "Unit"],
    ["EV006", "Electric Bus", "P026", "Cooling Pump", 4, "Unit"],
    ["EV006", "Electric Bus", "P027", "Cooling Fan", 4, "Unit"],
    ["EV006", "Electric Bus", "P028", "Radiator", 2, "Unit"],

    ["EV006", "Electric Bus", "P030", "High Voltage Cable", 30, "Meter"],
    ["EV006", "Electric Bus", "P031", "Wiring Harness", 2, "Unit"],
    ["EV006", "Electric Bus", "P032", "12V Auxiliary Battery", 2, "Unit"],
    ["EV006", "Electric Bus", "P034", "Vehicle Control Unit", 1, "Unit"],
    ["EV006", "Electric Bus", "P035", "Electronic Control Module", 5, "Unit"],
    ["EV006", "Electric Bus", "P036", "CAN Communication Module", 2, "Unit"],
    ["EV006", "Electric Bus", "P038", "Insulation Monitoring Device", 2, "Unit"],
    ["EV006", "Electric Bus", "P040", "Emergency Disconnect", 2, "Unit"],

    ["EV006", "Electric Bus", "P041", "Vehicle Chassis", 1, "Unit"],
    ["EV006", "Electric Bus", "P042", "Suspension Assembly", 6, "Unit"],
    ["EV006", "Electric Bus", "P043", "Brake Assembly", 6, "Unit"],
    ["EV006", "Electric Bus", "P044", "Steering Assembly", 1, "Unit"],
    ["EV006", "Electric Bus", "P045", "Wheel Assembly", 6, "Unit"],


    # ==========================================================
    # ELECTRIC HGV / TRUCK
    # ==========================================================

    ["EV007", "Electric HGV/Truck", "P001", "Battery Pack", 1, "Unit"],
    ["EV007", "Electric HGV/Truck", "P003", "Battery Management System", 1, "Unit"],
    ["EV007", "Electric HGV/Truck", "P004", "Battery Module", 12, "Unit"],
    ["EV007", "Electric HGV/Truck", "P005", "Battery Enclosure", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P009", "Battery Cooling Plate", 12, "Unit"],

    ["EV007", "Electric HGV/Truck", "P011", "Electric Motor", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P012", "Motor Controller", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P013", "Reduction Gearbox", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P014", "Differential", 2, "Unit"],

    ["EV007", "Electric HGV/Truck", "P016", "Inverter", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P017", "DC-DC Converter", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P018", "Power Distribution Unit", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P019", "High Voltage Contactor", 8, "Unit"],
    ["EV007", "Electric HGV/Truck", "P020", "High Voltage Fuse", 6, "Unit"],

    ["EV007", "Electric HGV/Truck", "P021", "On-board Charger", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P022", "Charging Port", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P024", "High Voltage Connector", 12, "Unit"],

    ["EV007", "Electric HGV/Truck", "P025", "Thermal Management System", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P026", "Cooling Pump", 4, "Unit"],
    ["EV007", "Electric HGV/Truck", "P027", "Cooling Fan", 4, "Unit"],
    ["EV007", "Electric HGV/Truck", "P028", "Radiator", 2, "Unit"],

    ["EV007", "Electric HGV/Truck", "P030", "High Voltage Cable", 40, "Meter"],
    ["EV007", "Electric HGV/Truck", "P031", "Wiring Harness", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P032", "12V Auxiliary Battery", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P034", "Vehicle Control Unit", 1, "Unit"],
    ["EV007", "Electric HGV/Truck", "P035", "Electronic Control Module", 5, "Unit"],
    ["EV007", "Electric HGV/Truck", "P036", "CAN Communication Module", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P038", "Insulation Monitoring Device", 2, "Unit"],
    ["EV007", "Electric HGV/Truck", "P040", "Emergency Disconnect", 2, "Unit"],

    ["EV007", "Electric HGV/Truck", "P041", "Vehicle Chassis", 1, "Unit"],
    ["EV007", "Electric HGV/Truck", "P042", "Suspension Assembly", 6, "Unit"],
    ["EV007", "Electric HGV/Truck", "P043", "Brake Assembly", 6, "Unit"],
    ["EV007", "Electric HGV/Truck", "P044", "Steering Assembly", 1, "Unit"],
    ["EV007", "Electric HGV/Truck", "P045", "Wheel Assembly", 6, "Unit"]
]

vehicle_bom_df = pd.DataFrame(
    bom_data,
    columns=[
        "vehicle_id",
        "vehicle_type",
        "part_id",
        "part_name",
        "quantity_per_vehicle",
        "unit"
    ]
)

print("Shape:", vehicle_bom_df.shape)

display(vehicle_bom_df.head(20))

Shape: (167, 6)

,vehicle_id,vehicle_type,part_id,part_name,quantity_per_vehicle,unit
0,EV001,Electric 2W,P001,Battery Pack,1,Unit
1,EV001,Electric 2W,P002,Battery Cells,1,Set
2,EV001,Electric 2W,P003,Battery Management System,1,Unit
3,EV001,Electric 2W,P011,Electric Motor,1,Unit
4,EV001,Electric 2W,P012,Motor Controller,1,Unit
5,EV001,Electric 2W,P017,DC-DC Converter,1,Unit
6,EV001,Electric 2W,P022,Charging Port,1,Unit
7,EV001,Electric 2W,P023,Charging Cable,1,Unit
8,EV001,Electric 2W,P030,High Voltage Cable,1,Meter
9,EV001,Electric 2W,P031,Wiring Harness,1,Unit
10,EV001,Electric 2W,P032,12V Auxiliary Battery,1,Unit
11,EV002,Electric 3W Passenger,P001,Battery Pack,1,Unit
12,EV002,Electric 3W Passenger,P002,Battery Cells,1,Set
13,EV002,Electric 3W Passenger,P003,Battery Management System,1,Unit
14,EV002,Electric 3W Passenger,P011,Electric Motor,1,Unit
15,EV002,Electric 3W Passenger,P012,Motor Controller,1,Unit
16,EV002,Electric 3W Passenger,P016,Inverter,1,Unit
17,EV002,Electric 3W Passenger,P017,DC-DC Converter,1,Unit
18,EV002,Electric 3W Passenger,P022,Charging Port,1,Unit
19,EV002,Electric 3W Passenger,P023,Charging Cable,1,Unit

In [5]:
bom_summary = (
    vehicle_bom_df
    .groupby(["vehicle_id", "vehicle_type"])
    .agg(
        component_count=("part_id", "count"),
        total_component_quantity=("quantity_per_vehicle", "sum")
    )
    .reset_index()
)

display(bom_summary)

  vehicle_id           vehicle_type  component_count  total_component_quantity
0      EV001            Electric 2W               11                        11
1      EV002  Electric 3W Passenger               12                        13
2      EV003      Electric 3W Goods               12                        13
3      EV004           Electric Car               43                        85
4      EV005           Electric LGV               19                        35
5      EV006           Electric Bus               36                       143
6      EV007     Electric HGV/Truck               34                       160

In [6]:
print(component_master_df.shape)

display(
    component_master_df[
        ["part_id", "part_name", "category"]
    ]
)

(45, 6)

   part_id                     part_name           category
0     P001                  Battery Pack            Battery
1     P002                 Battery Cells            Battery
2     P003     Battery Management System            Battery
3     P004                Battery Module            Battery
4     P005             Battery Enclosure            Battery
5     P006                        Busbar            Battery
6     P007                Cell Connector            Battery
7     P008                Battery Sensor            Battery
8     P009         Battery Cooling Plate            Battery
9     P010     Battery Safety Disconnect            Battery
10    P011                Electric Motor         Powertrain
11    P012              Motor Controller         Powertrain
12    P013             Reduction Gearbox         Powertrain
13    P014                  Differential         Powertrain
14    P015                   Drive Shaft         Powertrain
15    P016                      Inverter  Power Electronics
16    P017               DC-DC Converter  Power Electronics
17    P018       Power Distribution Unit  Power Electronics
18    P019        High Voltage Contactor  Power Electronics
19    P020             High Voltage Fuse  Power Electronics
20    P021              On-board Charger           Charging
21    P022                 Charging Port           Charging
22    P023                Charging Cable           Charging
23    P024        High Voltage Connector           Charging
24    P025     Thermal Management System            Thermal
25    P026                  Cooling Pump            Thermal
26    P027                   Cooling Fan            Thermal
27    P028                      Radiator            Thermal
28    P029                       Coolant            Thermal
29    P030            High Voltage Cable         Electrical
30    P031                Wiring Harness         Electrical
31    P032         12V Auxiliary Battery         Electrical
32    P033         Low Voltage Connector         Electrical
33    P034          Vehicle Control Unit        Electronics
34    P035     Electronic Control Module        Electronics
35    P036      CAN Communication Module        Electronics
36    P037          Vehicle Display Unit        Electronics
37    P038  Insulation Monitoring Device             Safety
38    P039                  Crash Sensor             Safety
39    P040          Emergency Disconnect             Safety
40    P041               Vehicle Chassis         Mechanical
41    P042           Suspension Assembly         Mechanical
42    P043                Brake Assembly         Mechanical
43    P044             Steering Assembly         Mechanical
44    P045                Wheel Assembly         Mechanical

In [7]:
import pandas as pd
import numpy as np

np.random.seed(42)

warehouses = [
    "Chennai",
    "Hosur",
    "Coimbatore",
    "Chengalpattu"
]

inventory_data = []

for _, part in component_master_df.iterrows():

    for warehouse in warehouses:

        part_id = part["part_id"]
        part_name = part["part_name"]

        # Different stock levels for different components
        available_stock = np.random.randint(500, 10000)

        # Safety stock
        safety_stock = int(
            available_stock * np.random.uniform(0.10, 0.25)
        )

        # Reorder level should be higher than safety stock
        reorder_level = int(
            safety_stock * np.random.uniform(1.5, 2.5)
        )

        # Determine inventory status
        if available_stock <= safety_stock:
            inventory_status = "Critical"

        elif available_stock <= reorder_level:
            inventory_status = "Reorder"

        else:
            inventory_status = "Healthy"

        inventory_data.append([
            part_id,
            part_name,
            warehouse,
            available_stock,
            safety_stock,
            reorder_level,
            inventory_status
        ])


inventory_df = pd.DataFrame(
    inventory_data,
    columns=[
        "part_id",
        "part_name",
        "warehouse",
        "available_stock",
        "safety_stock",
        "reorder_level",
        "inventory_status"
    ]
)

print("Shape:", inventory_df.shape)

display(inventory_df.head(20))

Shape: (180, 7)

,part_id,part_name,warehouse,available_stock,safety_stock,reorder_level,inventory_status
0,P001,Battery Pack,Chennai,7770,1705,2870,Healthy
1,P001,Battery Pack,Hosur,5691,1080,1788,Healthy
2,P001,Battery Pack,Coimbatore,966,111,217,Healthy
3,P001,Battery Pack,Chengalpattu,8822,909,2245,Healthy
4,P002,Battery Cells,Chennai,7449,745,1856,Healthy
5,P002,Battery Cells,Hosur,1684,245,496,Healthy
6,P002,Battery Cells,Coimbatore,9166,1757,2880,Healthy
7,P002,Battery Cells,Chengalpattu,3247,503,983,Healthy
8,P003,Battery Management System,Chennai,3234,623,1172,Healthy
9,P003,Battery Management System,Hosur,1767,333,514,Healthy
10,P003,Battery Management System,Coimbatore,4390,886,1728,Healthy
11,P003,Battery Management System,Chengalpattu,5893,1428,3520,Healthy
12,P004,Battery Module,Chennai,8933,1409,2135,Healthy
13,P004,Battery Module,Hosur,7541,1528,2964,Healthy
14,P004,Battery Module,Coimbatore,1275,134,322,Healthy
15,P004,Battery Module,Chengalpattu,2085,415,751,Healthy
16,P005,Battery Enclosure,Chennai,4343,554,1368,Healthy
17,P005,Battery Enclosure,Hosur,7373,1234,2338,Healthy
18,P005,Battery Enclosure,Coimbatore,1495,283,685,Healthy
19,P005,Battery Enclosure,Chengalpattu,8129,1051,1624,Healthy

In [9]:
reorder_items = inventory_df[
    inventory_df["inventory_status"].isin(
        ["Reorder", "Critical"]
    )
]

display(
    reorder_items.sort_values(
        "available_stock"
    )
)

Empty DataFrame
Columns: [part_id, part_name, warehouse, available_stock, safety_stock, reorder_level, inventory_status]
Index: []

In [10]:
inventory_df["stock_ratio"] = (
    inventory_df["available_stock"]
    /
    inventory_df["reorder_level"]
)